#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_hd1 = \
SortingTest.h \
generator.h 

SRCS_cppd1 = \
generator.cpp \
main.cpp \
SortingTest.cpp 

SRCS_fd1 = \
CM.f 

OBJS_hd1 = \


OBJS_cppd1 = \
generator.o \
main.o \
SortingTest.o 

OBJS_fd1 = \
CM.o 

SRC_DIR_hd1 = 

SRC_DIR_cppd1 = 

SRC_DIR_fd1 = 
OBJS_DIR = obj/Release/
EXE_DIR = bin/Release/

EXE = test.exe
FC = mingw32-gcc.exe
LD = mingw32-g++.exe
IDIR = 
CFLAGS = -Wall -fexceptions -O2 -std=c++11  -J$(OBJS_DIR) $(IDIR)
LFLAGS = -s 
LIBS = 

VPATH = $(SRC_DIR_hd1):$(OBJS_DIR):$(SRC_DIR_cppd1):$(OBJS_DIR):$(SRC_DIR_fd1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_hd1) $(OBJS_cppd1) $(OBJS_fd1))

all : $(EXE)

$(EXE) : $(OBJS_hd1) $(OBJS_cppd1) $(OBJS_fd1)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_hd1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_hd1)$(@:.o=.h) -o $(OBJS_DIR)$@

$(OBJS_cppd1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_cppd1)$(@:.o=.cpp) -o $(OBJS_DIR)$@

$(OBJS_fd1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_fd1)$(@:.o=.f) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
CM.o: \
    CM.f

